### ISSUE TITLE
Link for Dynamic Reports video is not working

### ISSUE THREAD

**Issue by DiptimanBadajena** [AdobeDocs/campaign-standard.en#10]
Issue in ./help/reporting/using/about-dynamic-reports.md

When clicking on dynamic report video link, it redirects to https://docs.adobe.com/content/help/en/campaign-learn/campaign-standard-tutorials/getting-started/creating-a-dynamic-report.html, which is not accessible/available.

**Comment by Alicesnk** [comment]
the issue is now solved
https://docs.adobe.com/content/help/en/campaign-standard/using/reporting/about-reporting/about-dynamic-reports.html
