### ISSUE TITLE
Image source personalization not working

### ISSUE THREAD

**Issue by GayathriRamasamy** [AdobeDocs/campaign-standard.en#2]
Issue in ./help/designing/using/personalization.md
While personalize the image source , the source of the image shows unknown that means if I paste url/(personalizedfeild).jpg the image source shows <img src="url/.jpg" only not  adding the personalized field

![image](https://user-images.githubusercontent.com/22314329/160119452-a41f8877-3254-4a78-9c36-02ae9f48fe6f.png)

**Comment by Alicesnk** [comment]
Hi @GayathriRamasamy, thanks for your feedback. Best option is to contact Adobe Customer Care to find a resolution. Based on the outcome, we can add guidance and recommendations in the documentation.
