### ISSUE TITLE
Throughput and Timeouts

### ISSUE THREAD

**Issue by amymacchiarola** [AdobeDocs/campaign-standard.en#24]
Issue in ./help/administration/using/configuring-sms-channel.md
6. does not provide any information on these settings and is missing a screen capture of the related fields

![TPS and timeouts](https://user-images.githubusercontent.com/72840606/95930136-c1efbd80-0d93-11eb-8667-8218a786647e.JPG)

**Comment by amymacchiarola** [comment]
i need information on all fields on this section: Sending Window, Time before reconnection, Expiration period of the MT

**Comment by manbeneat** [comment]
Hi,
You can find more information related to SMS configuration in this [page](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=neolane&title=SMS+connector+protocol+and+settings#SMSconnectorprotocolandsettings-Throughputandtimeouts).
Hope this helps!

**Comment by amymacchiarola** [comment]
This is not helpful I cannot get to that wiki page.  Your external documentation does not explain these settings (throughput and timeouts) and is missing a screen capture of the related fields.  Please provide this information and update your doc.

**Comment by manbeneat** [comment]
Hi,

Sorry I added the wrong link, here is the documentation page: https://helpx.adobe.com/campaign/kb/sms-connector-protocol-and-settings.html#SMPPexternalaccountparameters
