### ISSUE TITLE
GDPR tutorials for ACS returns error

### ISSUE THREAD

**Issue by sebastianedberg** [AdobeDocs/campaign-standard.en#4]
Resource at '/content/help/en/campaign-learn/campaign-standard-tutorials/compliance/gdpr/gdpr-namespaces.html' not found: No resource found
Cannot serve request to /content/help/en/campaign-learn/campaign-standard-tutorials/compliance/gdpr/gdpr-namespaces.html on this server

ApacheSling/2.6 (jetty/9.4.20.v20190813, Java HotSpot(TM) 64-Bit Server VM 11.0.3, Linux 4.19.66-coreos amd64)

**Comment by Alicesnk** [comment]
New link is > https://docs.adobe.com/content/help/en/campaign-learn/campaign-standard-tutorials/privacy/namespaces-for-privacy-requests.html
The old page will be redirected soon. Thanks for your feedback
