### ISSUE TITLE
Connector field in screenshot is no longer available

### ISSUE THREAD

**Issue by Robsay** [AdobeDocs/campaign-standard.en#5]
Issue in ./help/administration/using/configuring-sms-channel.md

**Comment by juliette-massardier** [comment]
Thanks for spotting this. It's been updated and the changes will be published early January. Merry Christmas!

**Comment by Alicesnk** [comment]
The issue is now resolved
https://docs.adobe.com/content/help/en/campaign-standard/using/administrating/configuring-channels/configuring-sms-channel.html
