### ISSUE TITLE
Link incorrectly pointing to Typology rules page.

### ISSUE THREAD

**Issue by ietashish** [AdobeDocs/campaign-standard.en#6]
Issue in ./help/rn/using/release-notes.md

On release notes page, https://docs.adobe.com/content/help/en/campaign-standard/using/release-notes/release-notes.html under "Release 19.1 - February 2019" >  "Launch integration for Mobile App", the text is as follows:

> This release contains the integration of Adobe Campaign with the GA versions of Android and iOS extensions for Adobe Campaign Standard in Adobe Experience Platform Launch and Mobile SDKs. These extensions support push messaging, in-app messaging, and mobile app profile updates.
For more information, refer to the detailed documentation . 

The link for "detailed documentation" is correctly pointing to https://docs.adobe.com/content/help/en/campaign-standard/using/administrating/working-with-typology-rules/about-typology-rules.html#typology-rules

**Comment by Alicesnk** [comment]
Fixed
